### PR TITLE
TMGR-9: add new modal window with new animation powered by gsap

### PR DESCRIPTION
**Pull request by acrossoffwest**

### CODE REVIEW

**Comment by savayer** [comment]
Not sure we need library for this. Let me try to be responsible for animations. I like do it as well )

**Comment by acrossoffwest** [comment]
I decided to leave the component as it is and in further, and I'll figure out how to use it.

**Comment by acrossoffwest** [comment]
Just, leave gsap for me)

**Comment by savayer** [comment]
there is not animation by closing modal @acrossoffwest

**Pull request closed without merging**
